INSERT INTO vsms_country (id, country_name) VALUES (0, 'NA');
INSERT INTO vsms_country (id, country_name) VALUES (1, 'United States');
INSERT INTO vsms_country (id, country_name) VALUES (2, 'Canada');
INSERT INTO vsms_country (id, country_name) VALUES (3, 'Mexico');
INSERT INTO vsms_country (id, country_name) VALUES (4, 'Afghanistan');
INSERT INTO vsms_country (id, country_name) VALUES (5, 'Albania');
INSERT INTO vsms_country (id, country_name) VALUES (6, 'Algeria');
INSERT INTO vsms_country (id, country_name) VALUES (7, 'Andorra');
INSERT INTO vsms_country (id, country_name) VALUES (8, 'Angola');
INSERT INTO vsms_country (id, country_name) VALUES (9, 'Anguilla');
INSERT INTO vsms_country (id, country_name) VALUES (10, 'Antarctica');
INSERT INTO vsms_country (id, country_name) VALUES (11, 'Antigua and Barbuda');
INSERT INTO vsms_country (id, country_name) VALUES (12, 'Argentina');
INSERT INTO vsms_country (id, country_name) VALUES (13, 'Armenia');
INSERT INTO vsms_country (id, country_name) VALUES (14, 'Aruba');
INSERT INTO vsms_country (id, country_name) VALUES (15, 'Ascension Island');
INSERT INTO vsms_country (id, country_name) VALUES (16, 'Australia');
INSERT INTO vsms_country (id, country_name) VALUES (17, 'Austria');
INSERT INTO vsms_country (id, country_name) VALUES (18, 'Azerbaijan');
INSERT INTO vsms_country (id, country_name) VALUES (19, 'Bahamas');
INSERT INTO vsms_country (id, country_name) VALUES (20, 'Bahrain');
INSERT INTO vsms_country (id, country_name) VALUES (21, 'Bangladesh');
INSERT INTO vsms_country (id, country_name) VALUES (22, 'Barbados');
INSERT INTO vsms_country (id, country_name) VALUES (23, 'Belarus');
INSERT INTO vsms_country (id, country_name) VALUES (24, 'Belgium');
INSERT INTO vsms_country (id, country_name) VALUES (25, 'Belize');
INSERT INTO vsms_country (id, country_name) VALUES (26, 'Benin');
INSERT INTO vsms_country (id, country_name) VALUES (27, 'Bermuda');
INSERT INTO vsms_country (id, country_name) VALUES (28, 'Bhutan');
INSERT INTO vsms_country (id, country_name) VALUES (29, 'Bolivia');
INSERT INTO vsms_country (id, country_name) VALUES (30, 'Bophuthatswana');
INSERT INTO vsms_country (id, country_name) VALUES (31, 'Bosnia-Herzegovina');
INSERT INTO vsms_country (id, country_name) VALUES (32, 'Botswana');
INSERT INTO vsms_country (id, country_name) VALUES (33, 'Bouvet Island');
INSERT INTO vsms_country (id, country_name) VALUES (34, 'Brazil');
INSERT INTO vsms_country (id, country_name) VALUES (35, 'British Indian Ocean');
INSERT INTO vsms_country (id, country_name) VALUES (36, 'British Virgin Islands');
INSERT INTO vsms_country (id, country_name) VALUES (37, 'Brunei Darussalam');
INSERT INTO vsms_country (id, country_name) VALUES (38, 'Bulgaria');
INSERT INTO vsms_country (id, country_name) VALUES (39, 'Burkina Faso');
INSERT INTO vsms_country (id, country_name) VALUES (40, 'Burundi');
INSERT INTO vsms_country (id, country_name) VALUES (41, 'Cambodia');
INSERT INTO vsms_country (id, country_name) VALUES (42, 'Cameroon');
INSERT INTO vsms_country (id, country_name) VALUES (44, 'Cape Verde Island');
INSERT INTO vsms_country (id, country_name) VALUES (45, 'Cayman Islands');
INSERT INTO vsms_country (id, country_name) VALUES (46, 'Central Africa');
INSERT INTO vsms_country (id, country_name) VALUES (47, 'Chad');
INSERT INTO vsms_country (id, country_name) VALUES (48, 'Channel Islands');
INSERT INTO vsms_country (id, country_name) VALUES (49, 'Chile');
INSERT INTO vsms_country (id, country_name) VALUES (50, 'China, Peoples Republic');
INSERT INTO vsms_country (id, country_name) VALUES (51, 'Christmas Island');
INSERT INTO vsms_country (id, country_name) VALUES (52, 'Cocos (Keeling) Islands');
INSERT INTO vsms_country (id, country_name) VALUES (53, 'Colombia');
INSERT INTO vsms_country (id, country_name) VALUES (54, 'Comoros Islands');
INSERT INTO vsms_country (id, country_name) VALUES (55, 'Congo');
INSERT INTO vsms_country (id, country_name) VALUES (56, 'Cook Islands');
INSERT INTO vsms_country (id, country_name) VALUES (57, 'Costa Rica');
INSERT INTO vsms_country (id, country_name) VALUES (58, 'Croatia');
INSERT INTO vsms_country (id, country_name) VALUES (59, 'Cuba');
INSERT INTO vsms_country (id, country_name) VALUES (60, 'Cyprus');
INSERT INTO vsms_country (id, country_name) VALUES (61, 'Czech Republic');
INSERT INTO vsms_country (id, country_name) VALUES (62, 'Denmark');
INSERT INTO vsms_country (id, country_name) VALUES (63, 'Djibouti');
INSERT INTO vsms_country (id, country_name) VALUES (64, 'Dominica');
INSERT INTO vsms_country (id, country_name) VALUES (65, 'Dominican Republic');
INSERT INTO vsms_country (id, country_name) VALUES (66, 'Easter Island');
INSERT INTO vsms_country (id, country_name) VALUES (67, 'Ecuador');
INSERT INTO vsms_country (id, country_name) VALUES (68, 'Egypt');
INSERT INTO vsms_country (id, country_name) VALUES (69, 'El Salvador');
INSERT INTO vsms_country (id, country_name) VALUES (70, 'England');
INSERT INTO vsms_country (id, country_name) VALUES (71, 'Equatorial Guinea');
INSERT INTO vsms_country (id, country_name) VALUES (72, 'Estonia');
INSERT INTO vsms_country (id, country_name) VALUES (73, 'Ethiopia');
INSERT INTO vsms_country (id, country_name) VALUES (74, 'Falkland Islands');
INSERT INTO vsms_country (id, country_name) VALUES (75, 'Faeroe Islands');
INSERT INTO vsms_country (id, country_name) VALUES (76, 'Fiji');
INSERT INTO vsms_country (id, country_name) VALUES (77, 'Finland');
INSERT INTO vsms_country (id, country_name) VALUES (78, 'France');
INSERT INTO vsms_country (id, country_name) VALUES (79, 'French Guyana');
INSERT INTO vsms_country (id, country_name) VALUES (80, 'French Polynesia');
INSERT INTO vsms_country (id, country_name) VALUES (81, 'Gabon');
INSERT INTO vsms_country (id, country_name) VALUES (82, 'Gambia');
INSERT INTO vsms_country (id, country_name) VALUES (83, 'Georgia Republic');
INSERT INTO vsms_country (id, country_name) VALUES (84, 'Germany');
INSERT INTO vsms_country (id, country_name) VALUES (85, 'Gibraltar');
INSERT INTO vsms_country (id, country_name) VALUES (86, 'Greece');
INSERT INTO vsms_country (id, country_name) VALUES (87, 'Greenland');
INSERT INTO vsms_country (id, country_name) VALUES (88, 'Grenada');
INSERT INTO vsms_country (id, country_name) VALUES (89, 'Guadeloupe (French)');
INSERT INTO vsms_country (id, country_name) VALUES (90, 'Guatemala');
INSERT INTO vsms_country (id, country_name) VALUES (91, 'Guernsey Island');
INSERT INTO vsms_country (id, country_name) VALUES (92, 'Guinea Bissau');
INSERT INTO vsms_country (id, country_name) VALUES (93, 'Guinea');
INSERT INTO vsms_country (id, country_name) VALUES (94, 'Guyana');
INSERT INTO vsms_country (id, country_name) VALUES (95, 'Haiti');
INSERT INTO vsms_country (id, country_name) VALUES (96, 'Heard and McDonald Isls');
INSERT INTO vsms_country (id, country_name) VALUES (97, 'Honduras');
INSERT INTO vsms_country (id, country_name) VALUES (98, 'Hong Kong');
INSERT INTO vsms_country (id, country_name) VALUES (99, 'Hungary');
INSERT INTO vsms_country (id, country_name) VALUES (100, 'Iceland');
INSERT INTO vsms_country (id, country_name) VALUES (101, 'India');
INSERT INTO vsms_country (id, country_name) VALUES (102, 'Iran');
INSERT INTO vsms_country (id, country_name) VALUES (103, 'Iraq');
INSERT INTO vsms_country (id, country_name) VALUES (104, 'Ireland');
INSERT INTO vsms_country (id, country_name) VALUES (105, 'Isle of Man');
INSERT INTO vsms_country (id, country_name) VALUES (106, 'Israel');
INSERT INTO vsms_country (id, country_name) VALUES (107, 'Italy');
INSERT INTO vsms_country (id, country_name) VALUES (108, 'Ivory Coast');
INSERT INTO vsms_country (id, country_name) VALUES (109, 'Jamaica');
INSERT INTO vsms_country (id, country_name) VALUES (110, 'Japan');
INSERT INTO vsms_country (id, country_name) VALUES (111, 'Jersey Island');
INSERT INTO vsms_country (id, country_name) VALUES (112, 'Jordan');
INSERT INTO vsms_country (id, country_name) VALUES (113, 'Kazakhstan');
INSERT INTO vsms_country (id, country_name) VALUES (114, 'Kenya');
INSERT INTO vsms_country (id, country_name) VALUES (115, 'Kiribati');
INSERT INTO vsms_country (id, country_name) VALUES (116, 'Kuwait');
INSERT INTO vsms_country (id, country_name) VALUES (117, 'Laos');
INSERT INTO vsms_country (id, country_name) VALUES (118, 'Latvia');
INSERT INTO vsms_country (id, country_name) VALUES (119, 'Lebanon');
INSERT INTO vsms_country (id, country_name) VALUES (120, 'Lesotho');
INSERT INTO vsms_country (id, country_name) VALUES (121, 'Liberia');
INSERT INTO vsms_country (id, country_name) VALUES (122, 'Libya');
INSERT INTO vsms_country (id, country_name) VALUES (123, 'Liechtenstein');
INSERT INTO vsms_country (id, country_name) VALUES (124, 'Lithuania');
INSERT INTO vsms_country (id, country_name) VALUES (125, 'Luxembourg');
INSERT INTO vsms_country (id, country_name) VALUES (126, 'Macao');
INSERT INTO vsms_country (id, country_name) VALUES (127, 'Macedonia');
INSERT INTO vsms_country (id, country_name) VALUES (128, 'Madagascar');
INSERT INTO vsms_country (id, country_name) VALUES (129, 'Malawi');
INSERT INTO vsms_country (id, country_name) VALUES (130, 'Malaysia');
INSERT INTO vsms_country (id, country_name) VALUES (131, 'Maldives');
INSERT INTO vsms_country (id, country_name) VALUES (132, 'Mali');
INSERT INTO vsms_country (id, country_name) VALUES (133, 'Malta');
INSERT INTO vsms_country (id, country_name) VALUES (134, 'Martinique (French)');
INSERT INTO vsms_country (id, country_name) VALUES (135, 'Mauritania');
INSERT INTO vsms_country (id, country_name) VALUES (136, 'Mauritius');
INSERT INTO vsms_country (id, country_name) VALUES (137, 'Mayotte');
INSERT INTO vsms_country (id, country_name) VALUES (139, 'Micronesia');
INSERT INTO vsms_country (id, country_name) VALUES (140, 'Moldavia');
INSERT INTO vsms_country (id, country_name) VALUES (141, 'Monaco');
INSERT INTO vsms_country (id, country_name) VALUES (142, 'Mongolia');
INSERT INTO vsms_country (id, country_name) VALUES (143, 'Montenegro');
INSERT INTO vsms_country (id, country_name) VALUES (144, 'Montserrat');
INSERT INTO vsms_country (id, country_name) VALUES (145, 'Morocco');
INSERT INTO vsms_country (id, country_name) VALUES (146, 'Mozambique');
INSERT INTO vsms_country (id, country_name) VALUES (147, 'Myanmar');
INSERT INTO vsms_country (id, country_name) VALUES (148, 'Namibia');
INSERT INTO vsms_country (id, country_name) VALUES (149, 'Nauru');
INSERT INTO vsms_country (id, country_name) VALUES (150, 'Nepal');
INSERT INTO vsms_country (id, country_name) VALUES (151, 'Netherlands Antilles');
INSERT INTO vsms_country (id, country_name) VALUES (152, 'Netherlands');
INSERT INTO vsms_country (id, country_name) VALUES (153, 'New Caledonia (French)');
INSERT INTO vsms_country (id, country_name) VALUES (154, 'New Zealand');
INSERT INTO vsms_country (id, country_name) VALUES (155, 'Nicaragua');
INSERT INTO vsms_country (id, country_name) VALUES (156, 'Niger');
INSERT INTO vsms_country (id, country_name) VALUES (157, 'Niue');
INSERT INTO vsms_country (id, country_name) VALUES (158, 'Norfolk Island');
INSERT INTO vsms_country (id, country_name) VALUES (159, 'North Korea');
INSERT INTO vsms_country (id, country_name) VALUES (160, 'Northern Ireland');
INSERT INTO vsms_country (id, country_name) VALUES (161, 'Norway');
INSERT INTO vsms_country (id, country_name) VALUES (162, 'Oman');
INSERT INTO vsms_country (id, country_name) VALUES (163, 'Pakistan');
INSERT INTO vsms_country (id, country_name) VALUES (164, 'Panama');
INSERT INTO vsms_country (id, country_name) VALUES (165, 'Papua New Guinea');
INSERT INTO vsms_country (id, country_name) VALUES (166, 'Paraguay');
INSERT INTO vsms_country (id, country_name) VALUES (167, 'Peru');
INSERT INTO vsms_country (id, country_name) VALUES (168, 'Philippines');
INSERT INTO vsms_country (id, country_name) VALUES (169, 'Pitcairn Island');
INSERT INTO vsms_country (id, country_name) VALUES (170, 'Poland');
INSERT INTO vsms_country (id, country_name) VALUES (171, 'Polynesia (French)');
INSERT INTO vsms_country (id, country_name) VALUES (172, 'Portugal');
INSERT INTO vsms_country (id, country_name) VALUES (173, 'Qatar');
INSERT INTO vsms_country (id, country_name) VALUES (174, 'Reunion Island');
INSERT INTO vsms_country (id, country_name) VALUES (175, 'Romania');
INSERT INTO vsms_country (id, country_name) VALUES (176, 'Russia');
INSERT INTO vsms_country (id, country_name) VALUES (177, 'Rwanda');
INSERT INTO vsms_country (id, country_name) VALUES (178, 'S.Georgia Sandwich Isls');
INSERT INTO vsms_country (id, country_name) VALUES (179, 'Sao Tome, Principe');
INSERT INTO vsms_country (id, country_name) VALUES (180, 'San Marino');
INSERT INTO vsms_country (id, country_name) VALUES (181, 'Saudi Arabia');
INSERT INTO vsms_country (id, country_name) VALUES (182, 'Scotland');
INSERT INTO vsms_country (id, country_name) VALUES (183, 'Senegal');
INSERT INTO vsms_country (id, country_name) VALUES (184, 'Serbia');
INSERT INTO vsms_country (id, country_name) VALUES (185, 'Seychelles');
INSERT INTO vsms_country (id, country_name) VALUES (186, 'Shetland');
INSERT INTO vsms_country (id, country_name) VALUES (187, 'Sierra Leone');
INSERT INTO vsms_country (id, country_name) VALUES (188, 'Singapore');
INSERT INTO vsms_country (id, country_name) VALUES (189, 'Slovak Republic');
INSERT INTO vsms_country (id, country_name) VALUES (190, 'Slovenia');
INSERT INTO vsms_country (id, country_name) VALUES (191, 'Solomon Islands');
INSERT INTO vsms_country (id, country_name) VALUES (192, 'Somalia');
INSERT INTO vsms_country (id, country_name) VALUES (193, 'South Africa');
INSERT INTO vsms_country (id, country_name) VALUES (194, 'South Korea');
INSERT INTO vsms_country (id, country_name) VALUES (195, 'Spain');
INSERT INTO vsms_country (id, country_name) VALUES (196, 'Sri Lanka');
INSERT INTO vsms_country (id, country_name) VALUES (197, 'St. Helena');
INSERT INTO vsms_country (id, country_name) VALUES (198, 'St. Lucia');
INSERT INTO vsms_country (id, country_name) VALUES (199, 'St. Pierre Miquelon');
INSERT INTO vsms_country (id, country_name) VALUES (200, 'St. Martins');
INSERT INTO vsms_country (id, country_name) VALUES (201, 'St. Kitts Nevis Anguilla');
INSERT INTO vsms_country (id, country_name) VALUES (202, 'St. Vincent Grenadines');
INSERT INTO vsms_country (id, country_name) VALUES (203, 'Sudan');
INSERT INTO vsms_country (id, country_name) VALUES (204, 'Suriname');
INSERT INTO vsms_country (id, country_name) VALUES (205, 'Svalbard Jan Mayen');
INSERT INTO vsms_country (id, country_name) VALUES (206, 'Swaziland');
INSERT INTO vsms_country (id, country_name) VALUES (207, 'Sweden');
INSERT INTO vsms_country (id, country_name) VALUES (208, 'Switzerland');
INSERT INTO vsms_country (id, country_name) VALUES (209, 'Syria');
INSERT INTO vsms_country (id, country_name) VALUES (210, 'Tajikistan');
INSERT INTO vsms_country (id, country_name) VALUES (211, 'Taiwan');
INSERT INTO vsms_country (id, country_name) VALUES (212, 'Tahiti');
INSERT INTO vsms_country (id, country_name) VALUES (213, 'Tanzania');
INSERT INTO vsms_country (id, country_name) VALUES (214, 'Thailand');
INSERT INTO vsms_country (id, country_name) VALUES (215, 'Togo');
INSERT INTO vsms_country (id, country_name) VALUES (216, 'Tokelau');
INSERT INTO vsms_country (id, country_name) VALUES (217, 'Tonga');
INSERT INTO vsms_country (id, country_name) VALUES (218, 'Trinidad and Tobago');
INSERT INTO vsms_country (id, country_name) VALUES (219, 'Tunisia');
INSERT INTO vsms_country (id, country_name) VALUES (220, 'Turkmenistan');
INSERT INTO vsms_country (id, country_name) VALUES (221, 'Turks and Caicos Isls');
INSERT INTO vsms_country (id, country_name) VALUES (222, 'Tuvalu');
INSERT INTO vsms_country (id, country_name) VALUES (223, 'Uganda');
INSERT INTO vsms_country (id, country_name) VALUES (224, 'Ukraine');
INSERT INTO vsms_country (id, country_name) VALUES (225, 'United Arab Emirates');
INSERT INTO vsms_country (id, country_name) VALUES (226, 'Uruguay');
INSERT INTO vsms_country (id, country_name) VALUES (227, 'Uzbekistan');
INSERT INTO vsms_country (id, country_name) VALUES (228, 'Vanuatu');
INSERT INTO vsms_country (id, country_name) VALUES (229, 'Vatican City State');
INSERT INTO vsms_country (id, country_name) VALUES (230, 'Venezuela');
INSERT INTO vsms_country (id, country_name) VALUES (231, 'Vietnam');
INSERT INTO vsms_country (id, country_name) VALUES (232, 'Virgin Islands (Brit)');
INSERT INTO vsms_country (id, country_name) VALUES (233, 'Wales');
INSERT INTO vsms_country (id, country_name) VALUES (234, 'Wallis Futuna Islands');
INSERT INTO vsms_country (id, country_name) VALUES (235, 'Western Sahara');
INSERT INTO vsms_country (id, country_name) VALUES (236, 'Western Samoa');
INSERT INTO vsms_country (id, country_name) VALUES (237, 'Yemen');
INSERT INTO vsms_country (id, country_name) VALUES (238, 'Yugoslavia');
INSERT INTO vsms_country (id, country_name) VALUES (239, 'Zaire');
INSERT INTO vsms_country (id, country_name) VALUES (240, 'Zambia');
INSERT INTO vsms_country (id, country_name) VALUES (241, 'Zimbabwe');

INSERT INTO vsms_gender (id, gender_name) VALUES (0, 'NA');
INSERT INTO vsms_gender (id, gender_name) VALUES (1, 'Male');
INSERT INTO vsms_gender (id, gender_name) VALUES (2, 'Female');
INSERT INTO vsms_gender (id, gender_name) VALUES (3, 'Others');
